name: CD

on:
  push:
    # branches:
    #   - master
    tags:
      - "*"

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master

      - name: Get version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Show working directory
        run: ls -al

      - name: Extract all packages
        run: ls *.gz | xargs -n1 tar -xzf && ls *.zip | xargs -n1 unzip

      - name: Show working directory
        run: ls -al

      - name: Configure
        run: cd nginx-1.22.1 && ./configure
          --sbin-path=/usr/local/nginx/nginx
          --conf-path=/usr/local/nginx/nginx.conf
          --pid-path=/usr/local/nginx/nginx.pid
          --with-http_v2_module
          --with-http_ssl_module
          --with-http_ssl_preread_module
          --with-pcre=../pcre2-10.42
          --with-zlib=../zlib-1.2.13
          --with-openssl=../openssl-OpenSSL_1_1_1k
          --add-module=../njs-d25d92370bfd/nginx
          --add-module=../nginx-upload-module-master

      - name: Build
        run: cd nginx-1.22.1 && make build

      - name: Package
        run: mkdir -p ./release && tar -zcvf ./release/kc-nginx-`uname`.tar.gz nginx-1.22.1/objs

      - name: Set SHA
        if: matrix.os == 'macos-latest'
        id: shasum
        run: |
          echo ::set-output name=sha::"$(shasum -a 256 ./release/kc-nginx.tar.gz | awk '{printf $1}')"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          prerelease: false
          files: |
            ./release/*.tar.gz
            ./release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
